name: Fetch wiki page

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: Fetch wiki details
        run: |
          wiki_page_url="https://api.github.com/repos/nivi30/hello-world/wiki"
      
      - name: commit
        run: |
          git config --global user.email "nivethavelu.98@gmail.com"
          git config --global user.name "nivi30"
          git add details.txt
          git commit -m "update details"
          git push
